### ISSUE TITLE
Please use Moo instead of Moose

### ISSUE THREAD

**Issue by jonassmedegaard** [kjetilk/p5-dist-inkt-doap#1]
Hi,

Please consider refactoring to use Moo instead of Moose.

**Comment by kjetilk** [comment]
Yup, I can do it when Dist::Inkt does it. Thanks for filing https://github.com/tobyink/p5-dist-inkt/issues/2 too.

**Comment by tobyink** [comment]
I don't think switching to Moo would be very feasible. Too much metaprogramming involved.

**Comment by kjetilk** [comment]
OK, thanks a lot for the comment. Since it relies on meta programming (I wasn't aware), I think I'll close this.
